import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Cabin } from 'next/font/google'

import 'swiper/css'
import 'swiper/css/bundle'

const cabin = Cabin({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <Navbar />
        <main className="mt-10 overflow-x-hidden">{children}</main>
      </body>
    </html>
  )
}
