import Navbar from '@/sections/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Cabin } from 'next/font/google'

import 'swiper/css'
import 'swiper/css/bundle'
import Footer from '@/sections/Footer'

const cabin = Cabin({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <Navbar />
        <main className="overflow-x-hidden mt-20 mb-36 px-10 md:px-20">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
